#!/bin/python3

import sys
import math

def lowestTriangle(base, area):
    c=(2*area)/base
    return(math.ceil(c))

base, area = input().strip().split(' ')
base, area = [int(base), int(area)]
height = lowestTriangle(base, area)
print(height)
